### ISSUE TITLE
clarify whether tests are expected to pass or fail

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1414]
When in doubt, I'd like to delete these tests

Database-analytical_sample-extract-exhaustive.yaml
- instantiates a [ProcessedSample](https://microbiomedata.github.io/nmdc-schema/ProcessedSample/)

Database-analytical_sample-minimal.yaml
- https://microbiomedata.github.io/nmdc-schema/AnalyticalSample/

Study-genome_portal_identifiers.yaml
- https://microbiomedata.github.io/nmdc-schema/Study/

**Comment by aclum** [comment]
@turbomam What branch are you working in? I don't see these in the main branch. I didn't write ther first two yaml files but Study-genome_portal_identifiers.yaml I did write as a test for checking that slot [jgi_portal_study_identifiers](https://microbiomedata.github.io/nmdc-schema/jgi_portal_study_identifiers/) is working so that is expected to pass and I would like to keep it. It is possible that the recent changes to study modeling make this test fail but I'd assumed that would be addressed before a merge to main.

**Comment by kheal** [comment]
These examples no longer exist.
