### ISSUE TITLE
Is it too late to make `metap_gene_function_aggregation`'s name more similar to `functional_annotation_agg`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1461]
like `metaproteomics_functional_annotation_agg`?

**Comment by aclum** [comment]
This breaks a number of things things and therefore would argue is not a good use of time.
- collection with this name already exists in mongo
- code to add records is already written
- data portal ingest code is already written against the existing collection name

**Comment by turbomam** [comment]
OK. I really want to have uniform names, and especially avoid nicknames like "metaP" in the names of other elements.

Do you think it would become any **more** disruptive in the future to change the name? If not, then I don't mind passing on it now.

In the meantime, I will make a PR that adds some more textual annotations or grouping to these elements.

**Comment by turbomam** [comment]
schema elements for describing the aggregation of metaproteomics-based functional annotations haven't been merged into main yet, have they? They're in https://github.com/microbiomedata/nmdc-schema/pull/1309, right?

I guess I should have asked for different element names when that PR first came out.

**Comment by aclum** [comment]
No, that is not merged in yet, there are issues with the new slot with the range enforced as a boolean. https://github.com/microbiomedata/nmdc-schema/pull/1309 is the correct PR.  There is an opportunity with the re-iding to fix this, all the records in the current collection (metap_gene_function_aggregation) will be dropped since it is all legacy ids. There are just a lot of moving parts with the re-iding so I'm hesitant to add this.
