### ISSUE TITLE
Add catalyzed_by slot and create Class:Enzymne for Range.

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1564]

**Comment by mslarae13** [comment]
@JamesTessmer  is working on this bug

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/berkeley-schema-fy24/pull/37

**Comment by mslarae13** [comment]
@JamesTessmer any update here?

**Comment by JamesTessmer** [comment]
> @JamesTessmer any update here?

Oh yes sorry, i forgot to update this issue. The branch for this was merged in and we implemented a work around for the bug. @anastasiyaprymolenna just want to double check with you as well that this was merged in (sometimes i misremember).

**Comment by mslarae13** [comment]
@JamesTessmer @anastasiyaprymolenna  is it Class:Enzyme still or Class:ChemicalConversionProcess

**Comment by JamesTessmer** [comment]
There isn't a new Enzyme class, but there is a 'catalyzed_by' slot on ChemicalConversionProcess that has a range of the 'Solution' class which in turn has the slot 'has_solution_components', which in turn has a range of 'SolutionComponent' which has the slot 'compound' which can use the 'ProteolyticEnzymeEnum' as its range.

It's quite a chain, but that's how we've structured the schema to capture the enzyme data.

**Comment by turbomam** [comment]
Good discussion. 

Instead of using a mixture of syntaxes for schema elements (bare, with a prefix like 'Class:', in single quotes, or in backticks), let's just consistently turn the mentions of elements into links.

This literal string

```
[catalyzed_by](https://microbiomedata.github.io/berkeley-schema-fy24/catalyzed_by/)
```

will be displayed as the linked text:

[catalyzed_by](https://microbiomedata.github.io/berkeley-schema-fy24/catalyzed_by/)

There are point and click tools for doing that at the top of the editing window

**Comment by turbomam** [comment]
> quite a chain

That's true. How open are you to some refactoring?

**Comment by JamesTessmer** [comment]
> > quite a chain
> 
> That's true. How open are you to some refactoring?

I'm open to refactoring but I would definitely want to loop others in as well because I don't know what things we need to preserve, what level of granularity we need to keep, etc. for the data.

I believe there's also data currently being added to mongo or preparation for that happening now, so I would at least like to wait until that so we don't step on anyone's toes.

**Comment by anastasiyaprymolenna** [comment]
Enzyme's will not be considered separate from the new Substance class, rather the old ProteolyticEnzymeEnum has been wrapped up in a new `SubstanceCategoryEnum` in the Berkeley '24 schema. So this issue can be closed.
