### ISSUE TITLE
update has_calibration from Class: MetabolomicsAnalysisActivity

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1570]
has_calibration needs to be required only if a chromatographic_category is of type GC

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/berkeley-schema-fy24/pull/29

**Comment by mslarae13** [comment]
Also add data_caregory slot to data object to designate enum for instrument vs process

**Comment by mslarae13** [comment]
@brynnz22

**Comment by mslarae13** [comment]
Keep the schema change in berk. Don't remove it from NOM and metaB analysis. After the merge happens, migrate has_calibration. 
When we ingest the material processing steps, make this update
@brynnz22 please create an issue and link

**Comment by turbomam** [comment]
I'm having a hard time following this issue since informal names are being schema elements. Please consider linking.

What [DataObject](https://microbiomedata.github.io/berkeley-schema-fy24/DataObject/) slots will be populated in a [has_calibration](https://microbiomedata.github.io/berkeley-schema-fy24/has_calibration/) path?

What are the use cases for making a `has_calibration.DataObject` ?

**Comment by turbomam** [comment]
The `DataObject` will be a data file from a previous GC/MS acquisition.

**Comment by turbomam** [comment]
How do we tie together the calibration reagent with the `DataObject`

New Calibration class?

- pointer to DataObject
- internal/external
- mixture used

**Comment by brynnz22** [comment]
The refactoring of moving the `has_calibration` slot from the `WorkflowExecution` subclasses of `MetabolomicsAnalysis` and `NomAnalysis` to the newly created `MaterialProcessing` subclass of `ChromatographicSeparationProcess` requires a database migration. Since the metadata for the new `ChromatographicSeparationProcess` does not yet exist, it does not makes sense to do this migration as it would require creating instances of `ChromatographicSeparationProcess` and `ProcessedSamples` to which metadata does not yet exist (besides `has_calibration`). An ingest of sorts needs to happen to gather the rest of the metadata and keep track of the schema traversals. In order to move forward with syncing the Berkeley schema into main, and not allowing this to be a blocker as it will take some time, we are keeping `has_calibration` on the `NomAnalysis` and `MetabalomicsAnalysis` classes for now in addition to adding it to the `ChromatographicSeparationProcess` class. The `has_calibration` slot will be removed from the `WorkflowExecution` subclasses and a migration will happen after the ingest for the `MaterialProcessing` classes occurs.

**Comment by turbomam** [comment]
closing based on https://github.com/microbiomedata/berkeley-schema-fy24/pull/133#issuecomment-2087763687
