### ISSUE TITLE
https://w3id.org/nmdc/nmdc doesn't resolve to https://microbiomedata.github.io/nmdc-schema/

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-schema#1611]
...because there is no `nmdc` schema element. Should the w3id.org .htaccess file hard-code this particular redirect? should the redirect be handled by the runtime api?

**Comment by turbomam** [comment]
Each of the YAML files in https://github.com/microbiomedata/nmdc-schema/tree/main/src/schema has [it's own `id`](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/nmdc.yaml#L1)

Specifically, the `id` for the root of the schema, nmdc.yaml is `https://w3id.org/nmdc/nmdc`, so that's what remains when the various imports are all merged together

And therefore, `https://w3id.org/nmdc/nmdc` is displayed as the `id` for the [landing page in the auto-generated](https://microbiomedata.github.io/nmdc-schema/) documentation. Furthermore, the id is displayed as a clickable (but broken) link.

_Note: this landing page is technically information about the nmdc-schema [SchemaDefinition](https://linkml.io/linkml-model/latest/docs/SchemaDefinition/)_

I'm not sure what to say about this one. It would be nice if your resolver were magically aware of all of the `id`s in the schema, not just the ones assigned to classes, slots, enumerations, etc. On the other hand, there isn't much utility to this particular link: I believes it only appears on the auto-generated landing page, and presumably the target for the link would just be the auto-generated landing page! That's the behavior on the [MIxS documentation landing page](https://genomicsstandardsconsortium.github.io/mixs/)

@sujaypatil96 @cmungall what do you think of either removing the SchemaDefinition's `id` altogether, or just disabling the link?
