### ISSUE TITLE
still some slots we need to move from DataGeneration to NucleotideSequencing 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1760]
There some slots that are inheriting to MassSpectrometry that shouldn't, like ncbi_project_name, [gold_sequencing_project_identifiers](https://microbiomedata.github.io/berkeley-schema-fy24/gold_sequencing_project_identifiers/). We should move these to be to NucleotideSequencing

cc @mslarae13

**Comment by mslarae13** [comment]
@bmeluch do you think you could work on this?

**Comment by bmeluch** [comment]
Of the slots in [DataGeneration](https://microbiomedata.github.io/berkeley-schema-fy24/DataGeneration/), it looks like the following should be moved to NucleotideSequencing because they are not relevant to MassSpectrometry:

- `gold_sequencing_project_identifiers`
- `insdc_bioproject_identifiers`
- `insdc_experiment_identifiers`
- `ncbi_project_name`
- `target_gene`
- `target_subfragment`
