### ISSUE TITLE
define "soft schema freeze" along with exceptions framework

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2033]
Especially seeking input from @mslarae13 @aclum @eecavanna @sierra-moxon @shreddd 

Steps
- [ ] identify the right place(s) to discuss this and save the decision

**Comment by turbomam** [comment]
see also
- https://github.com/microbiomedata/nmdc-schema/pull/2032

**Comment by eecavanna** [comment]
For the exceptions framework (decision framework), I propose this rule:
1. If the PR consists of changes to the `nmdc_schema/migrators` directory only, then it can be merged in after the typical developer-level review/approval (i.e. without a squad-level discussion/approval).

I expect that situation to arise multiple times during the soft schema freeze.

**Comment by mslarae13** [comment]
We can put the decision in the decision log? There's a note and decision logged in the metadata meeting note
- Schema changes that have any downstream effects will not be permitted after May 31st(June 14th). Downstream relates to requirements for runtime, workflows, products, or any other components of NMDC
- Changes to the schema that do not have downstream effects, are simply modeling changes that can be later implemented can be done on a branch and merged in AFTER review and evaluation.
  - Schema changes that don’t have downstream effects

Decision: Berkeley schema & nmdc-main schema changes should be reviewed and discussed with the team because nmdc-main schema is merged back into berk.

I'm good with @aclum & @eecavanna 's lists for more specific schema changes that don't have downstream effects.

@turbomam where would you like this more "officially" captured?

We also need to make a PR template. Not many people have provided feedback on what that template should look like

**Comment by turbomam** [comment]
@aclum  does you exception `1.` mean only python changes in `nmdc-schema` only, not `berkeley-schema-fy24`? I would want to all changes there too.

Otherwise I agree with the conclusions here.

**Comment by aclum** [comment]
1. would include python changes in both nmdc-schema, which would then get a back merge to berkeley-schema-fy24, and changes in berkeley-schema-fy24 if need to make them compatible with that version of the schema.

**Comment by eecavanna** [comment]
>We also need to make a PR template. Not many people have provided feedback on what that template should look like
https://github.com/microbiomedata/nmdc-schema/issues/1995

Noting that @mslarae13 recently introduced a PR template into `berkeley-schema-fy24` via PR https://github.com/microbiomedata/berkeley-schema-fy24/pull/217 and is in the process of introducing one into `nmdc-schema` via PR https://github.com/microbiomedata/nmdc-schema/pull/2105.

**Comment by mslarae13** [comment]
From the PR template

"
## _Soft_ Schema Freeze

The `nmdc-schema` and `berkeley-schema-fy24` schemas are under a soft freeze, which means changes **should not** be made that have any downstream implications. To ensure this, all PRs created creating during the freeze will be closely reviewed with **every** component of the NMDC system in mind.
"

Does that satisfy this issue @turbomam ? Or would you like this addressed somewhere else too?

**Comment by mslarae13** [comment]
Can we close this?  berkeley-schema is rolled out and the "soft freeze" was something, from the retro, we shouldn't do again. :)

**Comment by aclum** [comment]
+1 for closing

**Comment by eecavanna** [comment]
I'm also in favor of closing it.
