### ISSUE TITLE
long term: retire perl code that routes MIxS terms into NMDC schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#253]
see also #252

**Comment by turbomam** [comment]
Use mixs-source code. The most recently updated code is at https://github.com/turbomam/mixs-source, but that will be integrated into [https://github.com/GenomicsStandardsConsortium/mixs any day now.

**Comment by ssarrafan** [comment]
@sujaypatil96 Today is mid-sprint so I’m checking in to see how you’re doing with your assigned GitHub issues.  Please update this issue and let me know if you’re still actively working on it and it’s on track for finishing by the end of June. If you’re not working on it due to other priorities let me know if you plan to work on it in July or if it should be moved to the backlog for reprioritization.

**Comment by ssarrafan** [comment]
Checked with @sujaypatil96 and this one isn't high priority for next month so I'm removing from the sprint and adding the backlog label.

**Comment by turbomam** [comment]
now implemented with  [GNU make rules](https://github.com/microbiomedata/nmdc-schema/blob/main/project.Makefile#L89) and Python, especially using the sheets_and_friends package.
