### ISSUE TITLE
Integrate `materialize_patterns()` functionality into NMDC repo

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#329]
`materialize_patterns()` method has been added to core linkml now: https://github.com/linkml/linkml/blob/main/linkml/utils/pattern.py#L7

Once the next linkml release has been made we can start using this method. We need to figure out how to leverage this functionality using sheets_and_friends.

CC: @turbomam

**Comment by ssarrafan** [comment]
@sujaypatil96 Today is mid-sprint so I’m checking in to see how you’re doing with your assigned GitHub issues.  Please update this issue and let me know if you’re still actively working on it and it’s on track for finishing by the end of June. If you’re not working on it due to other priorities let me know if you plan to work on it in July or if it should be moved to the backlog for reprioritization.

**Comment by ssarrafan** [comment]
Moving to July sprint per @sujaypatil96

**Comment by ssarrafan** [comment]
@sujaypatil96 indicated this isn't a high priority anymore so removing from sprint and adding to backlog

**Comment by turbomam** [comment]
Structured patterns can be materialized with gen-linkml now. @cmungall has raised an issue in linkml/linkml suggesting the materialization of structured patterns should be the default behavior of the json schema generator.
