### ISSUE TITLE
Consolidate "oxygenation status of sample" and "relationship to oxygen"

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-schema#375]
from ESS attendees:

"oxygenation status of sample" and "relationship to oxygen" are very similar terms. There is currently no drop down selection enabled on "oxygenation status of sample".

@mslarae13 indicated that a decision was made during the GSC meeting this week to remove one term. This issue is for Montana to determine which one to remove then coordinate with @turbomam as needed.

**Comment by turbomam** [comment]
See also https://github.com/GenomicsStandardsConsortium/mixs/issues/440

**Comment by mslarae13** [comment]
Looks like GSC came to a different resolution. See Ramona's comment: https://github.com/GenomicsStandardsConsortium/mixs/issues/440#issuecomment-1202892190 

oxy_stat_samp is appropriate for some packages like soil, and it describes the (non-organismal) sample.

rel_to_oxygen can be used in certain checklists (e.g., MIGS, MIMARKS), but it is not mandatory in any of them. Just because something is in core, does not meet it has to be in everything (or even anything).

If I'm understanding that correctly. We should remove rel_to_oxygen as it's checklist specific, and we're focusing more on the sample. @cmungall , @turbomam , thoughts?

**Comment by turbomam** [comment]
I'm going to type this out in my own words, based on looking at [MIxS 6 term updates](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809), 

`oxy_stat_samp` is paired with several packages on the _MIxS6 packages - Final_clean_ tab. `rel_to_oxygen` is not mentioned on that tab.

`oxy_stat_samp`'s permissible values are [aerobic|anaerobic|other]

_MIxS6 Core- Final_clean_ follows the opposite pattern:  `rel_to_oxygen` is paired with several checklists , but `oxy_stat_samp` isn't mentioned.

`rel_to_oxygen` has the permissible values  [aerobe|anaerobe|facultative|microaerophilic|microanaerobe|obligate aerobe|obligate anaerobe]

I have no objection to removing `rel_to_oxygen` from our templates and only using `oxy_stat_samp` to express the apparently shared phenomenon. 

Do we feel like the permissible values for `oxy_stat_samp` are expressive enough?

**Comment by mslarae13** [comment]
@turbomam 

Those permissible values remind me why I also couldn't decide which to remove... rel_to_oxygen has more and better values.. but oxy_stat_sample being package specific makes more sense to keep.

I am curious if we can query the 2 values and see which is used more often & how it's used... are the other permissible values needed?

**Comment by mslarae13** [comment]
@ssarrafan overdue, please add to January 2023 sprint

**Comment by ssarrafan** [comment]
@mslarae13 moving to the next sprint, let me know if you don't plan to work on it in the next few weeks please

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/nmdc-schema/pull/689
