### ISSUE TITLE
`study_credit_test.json` file using `PersonValue` incorrectly

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#519]
There is a test in the nmdc-schema test suite that is causing issues when validated against the latest JSON Schema artifact in the repo. The latest JSON Schema artifact has been generated using `gen-json-schema` utility which leverages the SchemaView refactored JSON Schema generator. See https://github.com/linkml/linkml/pull/1054

The error is as follows:

```
{'type': 'PersonValue', 'orcid': 'orcid:0000-0002-1825-00'}: Additional properties are not allowed ('type' was unexpected)
{'type': 'PersonValue', 'orcid': 'orcid:0000-0001-9076-6066'}: Additional properties are not allowed ('type' was unexpected)
make: *** [Makefile:2[45](https://github.com/microbiomedata/nmdc-schema/actions/runs/3527080693/jobs/5915744119#step:9:46): validate-study_credit_test] Error 1
```

From @pkalita-lbl :

I’m going to say that it was working before because of some faulty assumptions made by `SchemaLoader` that you can’t get away with now that `SchemaView` is being used. See:
* [PersonValue itself does not have a type slot](https://github.com/microbiomedata/nmdc-schema/blob/4e30932f00f46d975878ec5258b0b80d52cb03cc/src/schema/core.yaml#L147)
* PersonValue is_a AttributeValue, but [AttributeValue doesn’t really have a type slot either](https://github.com/microbiomedata/nmdc-schema/blob/4e30932f00f46d975878ec5258b0b80d52cb03cc/src/schema/core.yaml#L101). I see it there in slot_usage but I don’t think it’s valid to reference something in slot_usage that isn’t also in slots

Couple of ways to resolve this issue are:
* remove the `type` property from the `PersonValue` class in the test itself like the JSON Schema error message says
* propose the addition of `type` slot either on `AttributeValue` or `PersonValue` classes

This is a schema change issue which needs more people's opinion.

CC: @pkalita-lbl @turbomam @cmungall

**Comment by pkalita-lbl** [comment]
It seems like the intention was for `AttributeValue` to have a `type` slot, but it just wasn't implemented correctly.

**Comment by turbomam** [comment]
I'm in favor of removing `type` from all classes, unless we apply some constraint that requires the value to be the name of an NMDC schema class. Currently, there are all sorts of junk `type` values in MongoDB

**Comment by turbomam** [comment]
I am removing the `type` mentions from the two test files
- test/data/study_credit_test.json
- test/data/invalid_schemas/study_credit_enum_mangle.json

That would be part of https://github.com/microbiomedata/nmdc-schema/pull/529, which I plan to merge with @cmungall's approval later today. 

We need a thorough audit of the usage of `type` in our MongoDB data, and the semantic implications of `type`'s definition in the schema. I removed the `slot_uri` of `rdf:type` because that creates invalid object relations in the OWL artifact, which I consider indicative of some deeper problem.

I we want an `nmdc:type` slot, and especially if we want it interpreted as `rdf:type`, then the only legal values must be `id`s for classes in the NMDC schema. As of now, there are lots of free form string values in MongoDB.

**Comment by aclum** [comment]
is this ticket obsolete post-berkeley

**Comment by turbomam** [comment]
> is this ticket obsolete post-berkeley

Yes, I think so. There isn't any study_credit_test.* file in nmdc-schema any more. I'll check the GH logs and probably close this in a few minutes.

**Comment by turbomam** [comment]
```shell
git log --follow -- study_credit_test.json
```

doesn't find anything
