### ISSUE TITLE
Submission Portal/ DH: samp_name should be required to be unique

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#581]
Issue:
samp_name (1st column, sample name) validates when the values are not unique. Like the source_mat_id (globally unique id) these should be required to be unique within a submission.

Completion:
Validation rule for samp_name is changed to require it be unique

- [ ] Provide Mark with some valid and in-valid examples - Montana
- [ ] Implement validation rule changes into the submission portal - Mark
- [ ] Present updates to the team - Montana

**Comment by mslarae13** [comment]
@turbomam 
Is this a schema, sheets and friends, or server issue?

**Comment by mslarae13** [comment]
@ssarrafan  & @turbomam can we put this in for sprint 2? Jan 3-13? as part of the submission portal squad deliverable "Align validation with expected values"

**Comment by turbomam** [comment]
I agree that `samp_name` should be unique, but don't have a direct answer to your schema/sheets and friends/server issue yet. We are currently enforcing uniqueness by applying a `identifier: true` assertion on `slot source_mat_id`. Unfortunately only one slot in a class can be the identifier. 

@cmungall has encouraged me to use [`unique_keys`](https://linkml.io/linkml/schemas/constraints.html#unique-key) to express multi-field uniqueness constraints but I have dragged my feet until now.

I'm not convinced that `unique_keys` will solve this problem from a pure LinkML perspective, and I'm even less confident that DataHarmonizer would pick up on the unique keys.

This is already illegal:

source_mat_id | samp_name
--|--
1 | a
1 | b

If we set `source_mat_id` **and** `samp_name` to be unique_keys, I think that will actually **become legal**, because there's two different composite keys. What we really want to require is both slots are required to be individually unique:

source_mat_id | samp_name
--|--
1 | a
2 | b

I will have to investigate some more.


Q from @sujaypatil96: could we make the parent slot from a slot group the identifier or the unique key?

**Comment by ssarrafan** [comment]
> @ssarrafan & @turbomam can we put this in for sprint 2? Jan 3-13? as part of the submission portal squad deliverable "Align validation with expected values"

Sure. I will put it under to do.

**Comment by mslarae13** [comment]
@ssarrafan  Assign to me for now. I've added a couple sub tasks to get this complete. Then Mark for actual implementation.

**Comment by mslarae13** [comment]
Difficult to accomplish. LinkML only allows for 1 identifier column, and that's the source_mat_id column and also must be unique.
LinkML has unique keys to use, but they aren't checked.
Longer lived issue, backlog.

**Comment by ssarrafan** [comment]
Removing from sprint, adding backlog label
@mslarae13

**Comment by turbomam** [comment]
`samp_name` is now considered a unique key. @pkalita-lbl has updated DataHarmonizer to apply the uniqueness constraint, but that has not appeared in a DH release yet.

**Comment by mslarae13** [comment]
The GUID (source_mat?) column should no longer be required. It's optional.. add a GUID IF you have a registered GUID. If you do not.. you'll get an NMDC minted ID.
So, we should be able to make sample_name the unique field

@pkalita-lbl  will this interrupt the multiple tabs? That relies on GUID right now, right?

**Comment by pkalita-lbl** [comment]
> will this interrupt the multiple tabs? That relies on GUID right now, right?

Yes, correct. We'll need to take that into account if we make that change.

**Comment by mslarae13** [comment]
> When does the NMDC identifier get minted for biosamples?

- source_mat_id should be optional
- rename globally unique ID back to source material id
- multi-tab code point to samp_name

**Comment by mslarae13** [comment]
nmdc biosample identifiers minting task is separate.. captured in an issue? 
submission portal to mongo connection.

**Comment by pkalita-lbl** [comment]
Schema changes are in. Once we release a new version of `submission-schema` we'll need to bring it into `nmdc-server` and make the required code changes over there.

**Comment by ssarrafan** [comment]
Moving to next sprint per @pkalita-lbl

**Comment by mslarae13** [comment]
@pkalita-lbl  should this be moved to in review? Or do we need another issue for the next step?

**Comment by pkalita-lbl** [comment]
This is still paused waiting for a new `submission-schema` release.

**Comment by pkalita-lbl** [comment]
These changes are now available on data-dev.microbiomedata.org
