### ISSUE TITLE
`id` no longer `required` by several schema classes as per JSON Schema

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-schema#852]
`biosample_set`, `collecting_biosamples_from_site_set`, and `field_research_site_set` items have `required` "id"s in the json schema representation, but others (e.g. `study_set`) do not. I can see e.g. that `Biosample` has an explicit `required: true` in its slot usage in the source YAML, whereas `Study` does not.

This impacts https://github.com/microbiomedata/nmdc-runtime/issues/240 because I would like duplicate-ID checking for json validation to be schema-driven.

/cc @sujaypatil96 @aclum

**Comment by dwinston** [comment]
> could I rephrase that as meaning that instances of class Study don't require id?

Yes

**Comment by turbomam** [comment]
Can you meet some time today?

I'm inclined to agree with your observation that a `Study` lacking an `id` is legal according to the jsonschema, although it is considered illegal by `linkml-run-examples`. I though that tool was based on jsonschema validation. although it probably builds its jsonschema form a YAML schemafile at runtime.

**Comment by turbomam** [comment]
@dwinston I can revisit this now. We should differentiate between 

1. cases in which `required` isn't asserted for `id` in some class' `slot_usage`
2. cases in which the `linkml-validator` or `linkml-run-examples` accepts a data file in which a `NamedThing` class is successfully instantiated without an `id`

Case 1. shouldn't matter, because `required` should be inherited from `NamedThing`. But I think there are some slot attributes that aren't getting propagated correctly, so this is a useful issue.

**Comment by aclum** [comment]
Was this resolved?
