### ISSUE TITLE
NEON soil metagenome story

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#917]
@aclum your example data and schema files were extremely helpful.

So far, I have copied and pasted, instead of merging. Then I have applied some modifications. Let me know how you want to reconcile what I have done to get good semantics, reuse, etc. vs what you need for the science.

**Comment by aclum** [comment]
Notes from the squad meeting
- [ ] Either new class Protocol or generic slots for protocol information (name and url )
- [ ] make extraction more generic and add to enum for valid values for extraction_type (DNA, RNA, metabolite, protein)
- [ ] figure out what to do with has_input/has_inputs and has_output/has_outputs for Classes (Pooling,Extraction, LIbraryPreparation). `has_inputs` and `has_outputs` inherits from class `PlannedProcess` so it is confusing to also allow slots `has_input` and/or `has_output`. Proposal: use `has_inputs` and `has_outputs` and specify cardinality explicitly for a class. Make these slots required, otherwise we'll have orphaned records.

**Comment by aclum** [comment]
@turbomam  I believe we are still missing syntax patterns for the new classes where we'll need to mint IDs
-ProcessedSample
-Pooling
-Extraction
-LibraryConstruction

**Comment by turbomam** [comment]
OK, I created a new issue for the identifier patterns and will complete it by mid day Monday.

- https://github.com/microbiomedata/nmdc-schema/issues/936

**Comment by ssarrafan** [comment]
@turbomam @aclum can this issue be closed? All checkboxes are complete and there is a new issue #936

**Comment by aclum** [comment]
Up to @turbomam but I'd prefer to leave this open since there are changes in the corresponding branch, https://github.com/microbiomedata/nmdc-schema/tree/issue-917-neon-story, which still need to be merged in related to slots for analytical samples as well as date slots for Class ProcessedSamples. This branch contains the example valid data for https://github.com/microbiomedata/nmdc-schema/issues/936 and https://github.com/microbiomedata/nmdc-schema/issues/908, https://github.com/microbiomedata/nmdc-schema/issues/906,https://github.com/microbiomedata/nmdc-schema/issues/937

**Comment by aclum** [comment]
Dependencies are resolved.
