### ISSUE TITLE
rename omics processing -> instrument process

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-schema#93]
from https://github.com/microbiomedata/nmdc-schema/pull/91#issuecomment-885764948

**Comment by wdduncan** [comment]
I think it might be better to have `instrument run` as a subclass of `omics processing`. We may have other kinds of `omics processing` we need to represent; e.g., kinds of sample preparation.

Also, although I prefer the label `instrument run` to `omics processing`, depending on how the above question is answered, it might be easier to add 'instrument run` as an alias to `omics processing`.

cc @dehays @turbomam

**Comment by dehays** [comment]
I would prefer to drop the term 'omics processing' entirely in favor of using more descriptive terms.  Even analysis activity could be 'omics processing'.  'omics' is too general. So the aim in my recommending 'instrument process' is in making the term clearer in our use.

That relates to the term we control - now following OBI, you have 'biosample processing' as a OBI material processing (OBI:0000094) : planned process which results in physical changes in a specified input material.  And you have 'omics processing' is_a biosample_processing and map it to OBI assay (OBI:0000070):  planned process with the objective to produce information about the material entity

I agree on the mapping of 'omics_processing' - what I am asking be renamed 'instrument process' - to OBI assay. It takes a physical material as input and produces information as output.  But I do not think it is_a biosample_processing (OBI material processing) because it does not produce a physical output.  If I am reading OBI correctly, assay and material processing are siblings, both share planned process as a parent.

I do not think that sample preparation would be a kind of what we currently call 'omics processing', an OBI assay.  I do think it would be a kind of what we call biosample processing (OBI material processing), specifically it would be OBI 'sample preparation for assay', OBI:0000073 which has OBI material processing as its parent.

Happy to discuss - also curious why OBI (and now NMDC) use gerunds in places of available nouns for terms?  Is there some reasoning there?  Why 'processing' instead of 'process' in some cases?

**Comment by wdduncan** [comment]
@dehays good questions! 
 - Re: gerunds: I cannot answer this. @cmungall is responsible for the creation of `omics processing`, but I suppose the "processing" bit is meant to draw attention to the notion that something is happening to the sample rather than that the material is doing something (e.g., material process may connote that the material is performing some process).
 - I agree with your analysis of the OBI mappings. The question (for me) is how much "ontological" rigor do we want in our mappings?  Broadly speaking, I think the idea was:
     - biosample processing -> process performed on samples
     - omics processing -> biosamples processings that produce omics information

If we rename `omics processing` to `instrument run`, I assume that entails that all such instrument runs produce omics information.

**Comment by turbomam** [comment]
Class now named `OmicsProcessing` (for future search-ability)

**Comment by turbomam** [comment]
This is still a pretty good suggestion, but will require a MongoDB migration and probably changes to nmdc-server too

**Comment by kheal** [comment]
This has been addressed in the Berkeley fork.  `OmicsProcessing` has been refactored into `DataGeneration` and its subclasses.
